FROM       ruby:2.6
LABEL      maintainer="Test Performance"

ENV        LANG C.UTF-8

WORKDIR    /app
COPY       Gemfile /app/
RUN        bundle install

COPY       linkextractor_nocache.rb /app/
RUN        chmod a+x linkextractor_nocache.rb

CMD        ["./linkextractor_nocache.rb", "-o", "0.0.0.0"]